name: CI for CPPMicroServices

on:
  pull_request:
    branches: 
      - master
      - development
  push: 
    branches:
      - master
      - development
  workflow_dispatch:
  
jobs:
  cmake:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.3
        with:
          cmake-version: '3.16.x'
      - uses: actions/checkout@v1
      - name: build
        run: cmake ./CMakeLists.txt
